'use strict';
Mite.rectsOverlap=(a,b)=>!!a&&!!b&&a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;
class EnemyBase{
 constructor(x,hp=2){this.x=x;this.spawnX=x;this.y=300;this.hp=hp;this.maxHp=hp;this.dead=false;this.remove=false;this.hitstun=0;this.flash=0;this.lastHit=-1;this.facing=-1;this.cooldown=0;this.state='idle';this.telegraph=0;this.active=false;}
 get body(){return{x:this.x-22,y:this.y-82,width:44,height:82};}
 damage(amount,dir){if(this.dead)return;this.active=true;this.hp-=amount;this.hitstun=.2;this.flash=.13;this.x+=dir*20;Mite.SFX?.hit();if(this.hp<=0){this.dead=true;this.hitstun=.55;this.state='down';Mite.SFX?.ko();}}
 tick(dt){this.hitstun=Math.max(0,this.hitstun-dt);this.flash=Math.max(0,this.flash-dt);this.cooldown=Math.max(0,this.cooldown-dt);this.telegraph=Math.max(0,this.telegraph-dt);if(this.dead){this.y+=95*dt;if(this.y>366)this.remove=true;}}
 shadow(ctx,stage,w=23){const sx=this.x-stage.cameraX;ctx.fillStyle='#050b1580';ctx.beginPath();ctx.ellipse(sx,stage.floor-1,w,5,0,0,Math.PI*2);ctx.fill();}
 drawArt(ctx,stage,img,w,h,dy=0){if(!img)return false;const x=Math.round(this.x-stage.cameraX),y=stage.floor;ctx.save();ctx.translate(x,y+dy);ctx.scale(this.facing,1);ctx.globalAlpha=this.flash>0?.42:1;let bob=0;if(this.state==='walk'||this.state==='retreat'||this.state==='charge')bob=(Math.floor(performance.now()/90)%2)*-2;if(this.state==='attack'||this.state==='throw'||this.state==='punch'||this.state==='heavy'||this.state==='rush')ctx.translate(3,0);ctx.drawImage(img,-w/2,-h+bob,w,h);ctx.restore();return true;}
 hpPips(ctx,x,y){if(this.maxHp<=3&&!this.dead){for(let i=0;i<this.maxHp;i++){ctx.fillStyle=i<this.hp?'#ff4d64':'#2b3240';ctx.fillRect(x-13+i*10,y-94,7,3);}}}
}
Mite.Yankee=class extends EnemyBase{
 constructor(x){super(x,2);this.attack=0;}
 update(dt,player,stage,world){this.tick(dt);if(this.dead)return;if(!this.active){if(Math.abs(player.x-this.spawnX)>470)return;this.active=true;}const d=player.x-this.x;this.facing=d>=0?1:-1;if(this.hitstun>0)return;if(this.attack>0){this.attack-=dt;this.state='attack';if(!this.didHit&&this.attack<.18&&this.attack>.10&&Math.abs(d)<72){this.didHit=true;if(player.hurt(9,this.x))world.shake=.10;}return;}
 if(Math.abs(d)>58){this.x+=Math.sign(d)*92*dt;this.state='walk';}else if(this.cooldown<=0){this.attack=.35;this.cooldown=1.18;this.didHit=false;this.state='windup';}else this.state='idle';this.x=Math.max(50,Math.min(stage.width-60,this.x));}
 draw(ctx,stage,images){this.shadow(ctx,stage);const x=Math.round(this.x-stage.cameraX),y=stage.floor;if(this.drawArt(ctx,stage,images&&images.yankee,76,110)){this.hpPips(ctx,x,y);return;}ctx.save();ctx.translate(x,y);ctx.scale(this.facing,1);ctx.globalAlpha=this.flash>0?.42:1;ctx.fillStyle='#151515';ctx.fillRect(-12,-78,24,19);ctx.fillStyle='#e9aa84';ctx.fillRect(-9,-60,19,20);ctx.fillStyle='#9d2035';ctx.fillRect(-18,-43,36,35);ctx.fillStyle='#29212a';ctx.fillRect(-19,-8,14,8);ctx.fillRect(5,-8,14,8);ctx.fillStyle='#e9aa84';const arm=this.attack>0&&this.attack<.23?30:19;ctx.fillRect(11,-39,arm,9);ctx.fillStyle='#f4c647';ctx.fillRect(-15,-73,28,4);ctx.restore();this.hpPips(ctx,x,y);}
};
Mite.Ninja=class extends EnemyBase{
 constructor(x){super(x,2);this.throwWind=0;this.didThrow=false;}
 update(dt,player,stage,world){this.tick(dt);if(this.dead)return;if(!this.active){if(Math.abs(player.x-this.spawnX)>540)return;this.active=true;}const d=player.x-this.x;this.facing=d>=0?1:-1;if(this.hitstun>0)return;const ad=Math.abs(d);if(this.throwWind>0){this.throwWind-=dt;this.state='throw';if(!this.didThrow&&this.throwWind<.10){this.didThrow=true;world.projectiles.push(new Mite.Acorn(this.x+this.facing*25,this.y-47,this.facing));Mite.SFX?.throw();}return;}
 if(ad<155){this.x-=Math.sign(d)*118*dt;this.state='retreat';}else if(ad>285){this.x+=Math.sign(d)*76*dt;this.state='walk';}else this.state='idle';if(this.cooldown<=0&&ad<430){this.cooldown=1.68;this.throwWind=.32;this.didThrow=false;this.telegraph=.2;}this.x=Math.max(70,Math.min(stage.width-70,this.x));}
 draw(ctx,stage,images){this.shadow(ctx,stage);const x=Math.round(this.x-stage.cameraX),y=stage.floor;if(this.drawArt(ctx,stage,images&&images.ninja,82,88)){if(this.throwWind>0){ctx.fillStyle='#ffd84a';ctx.fillRect(x+this.facing*42,y-63,4,4);}this.hpPips(ctx,x,y);return;}ctx.save();ctx.translate(x,y);ctx.scale(this.facing,1);ctx.globalAlpha=this.flash>0?.42:1;ctx.fillStyle='#3a241b';ctx.fillRect(-16,-70,32,56);ctx.fillStyle='#11151a';ctx.fillRect(-16,-57,32,19);ctx.fillStyle='#f2b184';ctx.fillRect(6,-50,8,6);ctx.fillStyle='#20120d';ctx.fillRect(-25,-12,19,10);ctx.fillRect(6,-12,19,10);ctx.fillStyle='#4c2d1e';ctx.fillRect(9,-38,this.throwWind>0?30:22,8);if(this.telegraph>0){ctx.fillStyle='#ffd84a';ctx.fillRect(28,-54,4,4);ctx.fillRect(35,-61,3,3);}ctx.restore();this.hpPips(ctx,x,y);}
};
Mite.HorseMan=class extends EnemyBase{
 constructor(x){super(x,2);this.phase='wait';this.timer=.75;this.speed=0;}
 update(dt,player,stage,world){this.tick(dt);if(this.dead)return;if(!this.active){if(Math.abs(player.x-this.spawnX)>520)return;this.active=true;}if(this.hitstun>0)return;this.timer-=dt;if(this.phase==='wait'){this.state='windup';this.telegraph=Math.max(this.telegraph,.08);if(this.timer<=0){this.phase='charge';this.facing=player.x>=this.x?1:-1;this.speed=410;this.state='charge';}}
 if(this.phase==='charge'){this.state='charge';this.x+=this.facing*this.speed*dt;if(Mite.rectsOverlap(this.body,player.body)&&player.hurt(16,this.x))world.shake=.18;const left=this.spawnX-250,right=this.spawnX+250;if(this.x<left||this.x>right){this.x=Math.max(left,Math.min(right,this.x));this.facing*=-1;this.timer=.58;this.phase='wait';}}}
 draw(ctx,stage,images){this.shadow(ctx,stage,29);const x=Math.round(this.x-stage.cameraX),y=stage.floor;if(this.drawArt(ctx,stage,images&&images.horseman,108,120)){if(this.phase==='wait'){ctx.fillStyle='#ff645f';ctx.fillRect(x+this.facing*52,y-103,5,15);}this.hpPips(ctx,x,y);return;}ctx.save();ctx.translate(x,y);ctx.scale(this.facing,1);ctx.globalAlpha=this.flash>0?.42:1;ctx.fillStyle='#e8a77e';ctx.fillRect(-22,-35,44,19);ctx.fillStyle='#24262b';ctx.fillRect(-25,-20,50,18);ctx.fillStyle='#e8a77e';ctx.fillRect(-9,-72,21,21);ctx.fillStyle='#f2f1ec';ctx.fillRect(-14,-53,30,19);ctx.fillStyle='#c83b31';ctx.fillRect(5,-53,5,26);ctx.fillStyle='#7a4a2a';ctx.fillRect(-20,-91,8,31);if(this.phase==='wait'){ctx.fillStyle='#ff645f';ctx.fillRect(23,-82,5,14);ctx.fillRect(23,-63,5,5);}ctx.restore();this.hpPips(ctx,x,y);}
};
Mite.Acorn=class{
 constructor(x,y,dir){this.x=x;this.y=y;this.dir=dir;this.remove=false;this.spin=0;}
 get body(){return{x:this.x-7,y:this.y-7,width:14,height:14};}
 update(dt,player,stage,world){this.x+=this.dir*255*dt;this.spin+=dt*18;if(Mite.rectsOverlap(this.body,player.body)){if(player.hurt(8,this.x))world.shake=.08;this.remove=true;}if(this.x<0||this.x>stage.width+40)this.remove=true;}
 draw(ctx,stage){const x=this.x-stage.cameraX;if(x<-30||x>670)return;ctx.save();ctx.translate(Math.round(x),Math.round(this.y));ctx.rotate(this.spin);ctx.fillStyle='#704224';ctx.fillRect(-6,-5,12,10);ctx.fillStyle='#3b2116';ctx.fillRect(-4,-8,8,4);ctx.restore();}
};
Mite.Boss=class extends EnemyBase{
 constructor(x){super(x,10);this.attackType='';this.attackTimer=0;this.name='JL BOSS';this.entered=false;}
 update(dt,player,stage,world){this.tick(dt);if(this.dead)return;if(!this.entered)return;this.active=true;const d=player.x-this.x,ad=Math.abs(d);this.facing=d>=0?1:-1;if(this.hitstun>0)return;if(this.attackTimer>0){this.attackTimer-=dt;this.state=this.attackType;if(this.attackType==='rush')this.x+=this.facing*225*dt;if(!this.didHit&&this.attackTimer<.27&&this.attackTimer>.16&&ad<96){this.didHit=true;if(player.hurt(this.attackType==='heavy'?19:12,this.x))world.shake=this.attackType==='heavy'?.2:.12;}return;}
 if(ad>92){this.x+=Math.sign(d)*80*dt;this.state='walk';}else this.state='idle';if(this.cooldown<=0&&ad<165){this.cooldown=1.12+Math.random()*.58;this.attackType=Math.random()<.32?'heavy':'punch';this.attackTimer=this.attackType==='heavy'?.62:.4;this.didHit=false;}else if(this.cooldown<=0&&ad>=165&&ad<350){this.cooldown=1.25;this.attackType='rush';this.attackTimer=.52;this.didHit=false;}this.x=Math.max(2820,Math.min(stage.width-70,this.x));}
 draw(ctx,stage,images){this.shadow(ctx,stage,27);const x=Math.round(this.x-stage.cameraX),y=stage.floor;if(this.drawArt(ctx,stage,images&&images.boss,88,116)){if(this.attackType==='heavy'&&this.attackTimer>.38){ctx.fillStyle='#ff534d';ctx.fillRect(x+this.facing*49,y-90,4,14);}return;}ctx.save();ctx.translate(x,y);ctx.scale(this.facing,1);ctx.globalAlpha=this.flash>0?.4:1;ctx.fillStyle='#0d0e12';ctx.fillRect(-23,-86,46,18);ctx.fillStyle='#f0ac78';ctx.fillRect(-17,-69,34,25);ctx.fillStyle='#6c4c31';ctx.fillRect(-9,-48,18,4);ctx.fillStyle='#17191e';ctx.fillRect(-26,-45,52,39);ctx.fillStyle='#eee';ctx.fillRect(-7,-42,14,29);ctx.fillStyle='#1b1c20';ctx.fillRect(-24,-8,19,8);ctx.fillRect(5,-8,19,8);ctx.fillStyle='#f0ac78';const reach=this.attackTimer>0?38:24;ctx.fillRect(14,-40,reach,11);ctx.fillStyle='#fff';ctx.font='bold 9px monospace';ctx.fillText('JL',-7,-73);if(this.attackType==='heavy'&&this.attackTimer>.38){ctx.fillStyle='#ff534d';ctx.fillRect(27,-68,4,12);ctx.fillRect(27,-51,4,4);}ctx.restore();}
};
